name: Create Branch and Commit

on:
  workflow_dispatch: # Trigger the workflow manually

jobs:
  create-branch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new branch
        run: |
          git checkout -b new-branch-name
          # Or, if you want to create a new branch and switch to it immediately:
          git checkout -b new-branch-name

      - name: Stage and Commit Changes
        run: |
          git config --global user.email "mspatagundi34@gmail.com"
          git config --global user.name "mspatagundi34"
          git add .
          git commit -m "Initial commit"
          git push -u origin new-branch-name
