name: Create Branch and Commit

on:
  workflow_dispatch: # Trigger the workflow manually
    inputs:
      feature_branch:
        description: 'Feature Branch Name'
        required: true
        default: 'feature-branch-2'

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt' 
          
      - name: Create a new branch
        run: |
          git checkout '${{ github.event.inputs.feature_branch }}' || git checkout -b '${{ github.event.inputs.feature_branch }}'
          # Or, if you want to create a new branch and switch to it immediately:
          # git checkout -b new-branch-name
          # git pull origin feature-branch-1

      - name: Set up Groovy
        uses: wtfjoke/setup-groovy@v2
        with:
          groovy-version: '4.x'  # Or specify a specific version like '4.0.9'

      - name: Run Groovy script
        run: |
          echo "Running Groovy script..."
          groovy .github/workflows/MuleMigration-v3.groovy
          echo "Groovy script finished."

      - name: Commit Changes
        run: |
          git config --local user.email "mspatagundi34@gmail.com"
          git config --local user.name "mspatagundi34"
          # git pull origin '${{ github.event.inputs.feature_branch }}'
          git add .
          git commit -m "Update project files and committed changes"
          # git push --set-upstream origin feature-branch-1
          # git push origin feature-branch-1
          git push -f origin '${{ github.event.inputs.feature_branch }}'
