name: Create Branch and Commit

on:
  workflow_dispatch: # Trigger the workflow manually

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
       
      - name: Create a new branch
        run: |
          git checkout -b new-branch-name
          # Or, if you want to create a new branch and switch to it immediately:
          # git checkout -b new-branch-name

      - name: Set Maven Version
        run: |
          mvn versions:set -DnewVersion="1.2.3"
        env:
          MAVEN_OPTS: -Dmaven.repo.local=~/.m2/repository

      - name: Commit Changes
        run: |
          git config --local user.email "mspatagundi34@gmail.com"
          git config --local user.name "mspatagundi34"
          git add .
          git commit -m "Update Maven artifact version to 1.2.3"
          git push
